spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://delivva-auth-service.ci4pk90j2559.us-east-1.rds.amazonaws.com:5432/delivva_auth
    username: delivva
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 646607232733-hufqatn96p95k8vprtfr0dpcr1h3elq4.apps.googleusercontent.com
            client-secret: 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
  rabbitmq:
    username: Delivva
    password: delivvadevelopers4
    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671

token:
  expiration:
    seconds: 1440 #in minutes

cloud:
  aws:
    s3bucket:
      name: delivva-auth-storage
      url: https://delivva-auth-storage.s3.amazonaws.com/
    credentials:
      access-key: AKIAXUNKWL54RPC5ENI3
      secret-key: 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
    region: us-east-1
    stack:
      auto: false
server:
  port: 5000

jwt:
  secret:
    key: 753778214125442A472IkphdZSIsImasV4cCIee6MTY4sdNzUwMTQwN3F452848567890iuyiu67567886578uyutuio78654678976549eyJS678965467uior678545
  access:
    expiry: 1440 #in minutes

rabbitmq:
  exchange:
    name: notification_direct_exchange
  routing:
    key: authorization_service_routing_key