spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://delivva-auth-service.ci4pk90j2559.us-east-1.rds.amazonaws.com:5432/delivva_auth
    username: delivva
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql    
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

token :
  expiration:
    seconds: 120

cloud:
  aws:
    s3bucket:
      name: ${AWS_S3_BUCKET_NAME}
      url: ${AWS_S3_URL}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    stack:
      auto: false
server:
  port: 5000