name: Delivva Authorization CD

on:
  push:
    branches: [develop]
jobs:
  test:
    services:
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout 'develop' branch
        run: |
          git fetch origin develop
          git checkout develop
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -X

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.16.26.65
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd Authorization_Service/
            git pull
            mvn clean install
              nohup java -jar target/authorization_service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &