name: OUR PROJECT

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.8
        env:
          DB_URL:jdbc: postgresql://postgres:5432/delivva_auth_db
          LOCAL_DB_URL: jdbc:postgresql://localhost:5432/delivva-authorization
          DB_USERNAME: postgres
          DB_PASSWORD: 6040
        ports:
          - 5432:5432
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'timurin'
            java-version: '17'
        - name: Build with Maven
          run: mvn clean install

        - name: RUn tests
          run: mvn test