name: DeLivva Authorization CI

on: [push]
jobs:
  run-test:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout 'develop' branch
        run: |
         git fetch origin develop
         git checkout develop
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Debug Logging
        run: |
          echo "POSTGRES_DB: ${{ secrets.POSTGRES_DB }}"
          echo "POSTGRES_USER: ${{ secrets.POSTGRES_USER }}"
          echo "POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}"