name: Spring boot CI-CD for delivva authentication service

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/authorization_service-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy project to AWS for testing environment
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_TEST_ENVIRONMENT }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY_TEST_ENVIRONMENT }}
<<<<<<< HEAD
          application_name:  test-vention-app
          environment_name: delivva-auth-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: authorization_service-0.0.1-SNAPSHOT.jar
=======
          application_name: delivva-testing-environment
          environment_name: Delivva-testing-environment-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: authorization_service-0.0.1-SNAPSHOT.jar
>>>>>>> develop
